%Inverse Transform matrix for taking frames local cordinates to global cordinates

a = input('Angle of element in degrees = ');
t = [cosd(a) sind(a) 0 0 0 0;...
    -sind(a) cosd(a) 0 0 0 0;...
    0 0 1 0 0 0;...
    0 0 0 cosd(a) sind(a) 0;...
    0 0 0 -sind(a) cosd(a) 0;...
    0 0 0 0 0 1]