%Local stiffness matrix for a truss element

d = input('Angle of element in degrees = ');
r = d*pi()/180  %conversion from degrees to radians
k = [cos(r)^2 sin(r)*cos(r) -cos(r)^2 -sin(r)*cos(r);...
    sin(r)*cos(r) sin(r)^2 -sin(r)*cos(r) -sin(r)^2;...
    -cos(r)^2 -sin(r)*cos(r) cos(r)^2 sin(r)*cos(r);...
    -sin(r)*cos(r) -sin(r)^2 sin(r)*cos(r) sin(r)^2]