%Inverse Transform matrix for taking global cordinates to local cordinates

a = input('Angle of element in degrees = ');
t = [cosd(a) sind(a) 0 0;...
    -sind(a) cosd(a) 0 0;...
    0 0 cosd(a) sind(a);...
    0 0 -sind(a) cosd(a)]